# Generated by Django 4.2.20 on 2025-03-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='/media/temp.jpg', upload_to='blog_images/'),
        ),
    ]
