# Generated by Django 4.2.20 on 2025-03-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='blog_images/temp.jpg', upload_to='blog_images/'),
        ),
    ]
